name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.100

    - name: Build assembly
      run: dotnet build source/CloudNative.CloudEvents.Endpoints.csproj

    - name: Create binary release
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet publish source/CloudNative.CloudEvents.Endpoints.csproj --configuration Release --output bin/Release
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: bin/Release